language: python
jobs:
  include:
    - stage: test
      python: "2.7"
      install: make install-test
      script: make test
    - python: "3.6"
    - python: "3.7-dev"
    - stage: deploy
      install: true
      script: true
      python: "3.6"
      deploy:
        provider: pypi
        distributions: bdist_egg
        user: emartech
        password: $PYPI_PASSWORD
        on:
          tags: true

