language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
jobs:
  include:
    - stage: test
      install: make install-test
      script: make test
    - stage: deploy
      script: skip
      python: "3.6"
      deploy:
        provider: pypi
        distributions: bdist_egg
        user: emartech
        password: $PYPI_PASSWORD
        on:
          tags: true

