language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
install: make install-test
script: make test
deploy:
  provider: pypi
  user: emartech
  password:
    secure: "iVMOXNTsv1cul0rmpE57ncRR56PZHEAYsx9UL2KTrevAjMLQnx6ikK0nzk9G01zFPUHUg6PpHzqNwKVT4gGGTlcyl3N8RD9+O09OCzS8aOuliDkT17veTGX5KvJMED0VXbzWOBcnEASPjVoOy9acQze6hxnzsgw4/A4/55yOEe9rDzKIT+T6/Q8WUf9mvCDTmUXZEddO9b/+qVihooC627BWkEpE4LiNPABLdV4ZIJxiIAWhuo4vL8ITv8Pjh2nHMzVK0q2tq+gen1vViROzWr1SBit4fPo0HKw+EhRnNzlpIhrL1b2igoLJTrR+cUcTPIHaXaRsOKTTkD5mNIIVkG7K3dX41Yut9/ITH9M+8mY3rSEt9WXtVVRie7mmK98fGgYshabykWQ9RdGC2ykFzC+AqURCMgXoPdCJ1h3ssEQ4ILTC1d86Kl2IXjCpAadmuNHoue58gJ7J4vwdf+K7yHoEohCH0a83Fr8zKImDoweNzpD2RxOF/A1fYBkXJBSOzFFQlRD5PAwr1nNcjNaVfy0D7qArSxHg/wF3qK+d8z/vQu+IoXkD+I3S9twwETHUzzyJQS+3L0jlkB2m5IOIPg7hGb9k9z0mEogegNfUZRLlNhOP+Y/zRXBTyOzwVxgJ5zJAqI7Y/+kYmINNWqE5emf5+JPw2k6xPQR20sjyI8o="

