language: python
jobs:
  include:
    - stage: test
      python:
        - "3.6.5"
        - "2.7"
        - "3.7-dev"
      install: make install-test
      script: make test
    - stage: deploy
      script: skip
      python: "3.6"
      deploy:
        provider: pypi
        distributions: bdist_egg
        user: emartech
        password: $PYPI_PASSWORD
        on:
          tags: true

