language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - CRYPTO=2.0.*
  - CRYPTO=2.1.*
  - CRYPTO=2.2.*
  - CRYPTO=2.3.*
  - CRYPTO=2.4.*
  - CRYPTO=2.5.*
  - CRYPTO=2.6.*
  - CRYPTO=2.7.*
  - CRYPTO=2.8.*

install:
  - pip install -q cryptography==$CRYPTO
  - pip install -e .[dev]

script:
  - python -m unittest discover test 'test_*.py'

jobs:
  include:
    - stage: deploy
      python: "3.8"
      env: "CRYPTO=2.8.*"
      deploy:
        provider: pypi
        distributions: "bdist_egg bdist_wheel sdist"
        user: emartech
        password: $PYPI_PASSWORD
        on:
          tags: true
